services:
  app:
    # コンテナ名を指定する
    container_name: kome_sanpo_app

    # ttyをtrueにすることでコンテナ内でのコマンド実行時に色々な情報を表示する
    tty: true

    # コンテナを起動する際に使用するネットワークを指定する
    # ネットワークを指定することでコンテナ間で通信が可能になる
    networks:
      - app_network

    # コンテナをビルドする際に使用するDockerfileのパスを指定する
    build:
      context: .

    # コンテナを起動する際に使用するポートを指定する
    ports:
      - "3000:3000"
      - "5555:5555"

    # コンテナを起動する際に使用するボリュームを指定する
    # ボリュームとはコンテナ内のデータをホスト側に保存するための仕組み
    volumes:
      - .:/app/
      - node_modules:/app/node_modules

    # 依存関係を持つコンテナが起動していることを確認する
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: kome_sanpo_db
    hostname: db
    env_file:
      - .env
    networks:
      - app_network
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  node_modules:
  db_data:

networks:
  app_network:
    driver: bridge
