import { Inter } from "next/font/google";

import type { Metadata } from "next";

import "./globals.css";
import { Button } from "@/features/common/components/Button";
import { Search } from "@/features/common/components/Search";
import { getSearch } from "@/lib/data";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const searchDate = await getSearch();
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="grid grid-cols-2-4-2 gap-6">
          <h1>こめさんぽ</h1>
          <Search placeholder="店名・ジャンルで検索" data={searchDate} />
          <Button>検索</Button>
        </header>
        {children}
      </body>
    </html>
  );
}
